import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/institute/side-bar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Institutes Dashboard",
  description: "Generated by Edu Master",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-[#0a0f1f] via-[#1b1037] to-[#2a1550] text-white`}
      >
        <div className="flex min-h-screen">
          <SidebarProvider>
            <AppSidebar />
            <main className="flex-1 flex flex-col">
              {/* Header */}
              <header className="bg-gradient-to-r from-purple-600 to-indigo-600 p-5 shadow-md border-b text-white border-white/10 sticky top-0 z-10">
                <div className="flex justify-between items-center">
                  <h1 className="text-2xl font-bold tracking-tight">
                    Institute Dashboard
                  </h1>
                </div>
              </header>

              {/* Main Content */}
              <div className="m-3  h-[90vh]  overflow-y-auto transition-all duration-300 relative">
              {/* bg-white/5  backdrop-blur-sm border border-white/10 
              shadow-xl w-full py-5 rounded-3xl */}
                <div
                  className="relative"
                >
                  {children}
                </div>
              </div>
              {/* Footer */}
              <footer className="bg-gradient-to-r from-purple-600 to-indigo-600 text-white p-4 text-center">
                <p className="text-sm">
                  © 2025 Edu Master. All rights reserved.
                </p>
              </footer>
            </main>
          </SidebarProvider>
        </div>
      </body>
    </html>
  );
}
